<a href="https://colab.research.google.com/github/BENMEZIAN/Data-Analysis-with-Python---freeCodeCamp--/blob/main/NumPy_freeCodeCamp_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy: Numeric Computing Library
######NumPy is one of the core packages for numerical computing in python. Pandas, Matplotlib, Statmodels and many other Scientific libraries rely on NumPy.

# Basic NumPy Arrays

In [88]:
import numpy as np
import sys

np.array([1,2,3,4])

a = np.array([1,2,3,4,5])

# Apply some slicing example on this array (a)
print(a[0], a[-1]) # 1 4
print(a[0:2]) # 1 2
print(a[::2]) # 1 3 5 (:: to skip elements)
print(a[[0, 2, -1]]) # concat indexes

# a[start:stop:step]
b = np.arange(20)

print("\n a = ",b)
print("\n a[-8:17:1] = ",b[-8:17:1]) # index (-8) starting from end, index 17 starting from beginning, step 1
print("\n a[10:] = ",b[10:]) # starting from index 10 to the end of the array

1 5
[1 2]
[1 3 5]
[1 3 5]

 a =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

 a[-8:17:1] =  [12 13 14 15 16]

 a[10:] =  [10 11 12 13 14 15 16 17 18 19]


###Array Types

In [56]:
# Print array types

a = np.array([1,2,3,4])

print("a :",a.dtype)

b = np.array([0, .5, 1, 1.5, 2])

print("b :",b.dtype)

c = np.array(['a', 'b', 'c'])

print("c :",c.dtype)

d = np.array([{'a': 1}, sys])

print("d :",d.dtype)

a : int64
b : float64
c : <U1
d : object


###Dimensions and shapes

In [55]:
# multidimensional array

a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print("Shapes (row,col):",a.shape)
print("Dimensions :",a.ndim,"D")
print("Size (number of elements):",a.size)

Shapes (row,col): (3, 3)
Dimensions : 2 D
Size (number of elements): 9


### Slicing Matrixes
https://www.geeksforgeeks.org/python/python-slicing-multi-dimensional-arrays/

In [95]:
# copy paste same matrix

a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

# Apply some slices please


b = a[0 , :] # first row [1,2,3]
b = a[1, :] # second row [4,5,6]
b = a[2, :] # third row [7,8,9]

b = a[: , 0] # first column [1 4 7]
b = a[: , 1] # second column [2,5,8]
b = a[: , 2] # third column [3,6,9]


# Do some random examples
sub_matrix = a[0:2, 1:3]  # always include the first index and exclude the end index
print("b = ",sub_matrix)
"""
b =  [[2 3]
      [5 6]]
"""

c  = a[::2, ::2]
print("c = ",c)
"""
c= [[1 3]
    [7 9]]
"""


b =  [[2 3]
 [5 6]]
c =  [[1 3]
 [7 9]]


'\nc= [[1 3]\n    [7 9]]\n'

### Summary Statistics

In [114]:
# 1D array

a = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
])

print("a.sum():",a.sum())
print("a.mean():",a.mean())
print("a.std():",a.std())
print("a.var():",a.var())
print("a.sum(axis = 0):",a.sum(axis=0)) # columns

if a.ndim > 1:
  print("a.sum(axis = 1):",a.sum(axis=1)) # rows

a.sum(): 55
a.mean(): 5.5
a.std(): 2.8722813232690143
a.var(): 8.25
a.sum(axis = 0): [ 7  9 11 13 15]
a.sum(axis = 1): [15 40]


# NumPy Operations


### Broadcasting and vectorization operation
https://www.geeksforgeeks.org/numpy/numpy-array-broadcasting/

In [132]:
# 1D array

a = np.arange(4)
print("a = ",a)
scalar = 10

# broadcast and vectorize array
b = np.array([10, 10, 10, 10])
c = np.array([4, 5, 6, 7])

print("a + b = ",a + b)
print("a * b = ",a * b)
print("a / b = ",a / b)

print("a + scalar = ",a + scalar)
print("a * scalar = ",a * scalar)
print("a / scalar = ",a / scalar)

# b with c
print("b + c = ",b + c)
print("b * c = ",b * c)
print("b / c = ",b / c)

ages = np.array([12, 24, 35, 45, 60, 72])
age_group = np.array(["Adult", "Minor"])
result = np.where(ages > 18, age_group[0], age_group[1])
print(result)

matrix = np.array([[1, 2], [3, 4]])
vector = np.array([10, 20])
result = matrix * vector
print(result)


a =  [0 1 2 3]
a + b =  [10 11 12 13]
a * b =  [ 0 10 20 30]
a / b =  [0.  0.1 0.2 0.3]
a + scalar =  [10 11 12 13]
a * scalar =  [ 0 10 20 30]
a / scalar =  [0.  0.1 0.2 0.3]
b + c =  [14 15 16 17]
b * c =  [40 50 60 70]
b / c =  [2.5        2.         1.66666667 1.42857143]
['Minor' 'Adult' 'Adult' 'Adult' 'Adult' 'Adult']
[[10 40]
 [30 80]]


# Boolean Arrays
https://www.geeksforgeeks.org/python/python-boolean-array-in-numpy/

In [144]:
a = np.array([1, 0, 1, 0, 0, 1, 0]) # 0 == False, any number else == True
b = a.astype(bool)
print(b)

# Using dtype='bool'
c = np.array([1, 0, 1, 0, 0, 1, 0], dtype='bool')
print(c)

# Using np.where
d = np.where(a == 1, True, False)
print(d)

# Using a comparison with 1
e = a == 1
print(e)


[ True False  True False False  True False]
[ True False  True False False  True False]
[ True False  True False False  True False]
[ True False  True False False  True False]


# NumPy Algebra & Size
https://www.geeksforgeeks.org/numpy/numpy-linear-algebra/

In [150]:
# Two 2D arrays and linear algebra operations, please

# Original singular matrix
# A = np.array([
#     [1, 2, 3],
#     [4, 5, 6],
#     [7, 8, 9]
# ])

# Use a non-singular matrix for inverse and power operations
A = np.array([
    [1, 2, 0],
    [0, 3, 1],
    [0, 0, 2]
])

print("Rank of A:", np.linalg.matrix_rank(A))
print("\nTrace of A:", np.trace(A))
print("\nDeterminant of A:", np.linalg.det(A))
print("\nInverse of A:\n", np.linalg.inv(A))
print("\nMatrix A raised to power 3:\n",np.linalg.matrix_power(A, 3))

Rank of A: 3

Trace of A: 6

Determinant of A: 6.0

Inverse of A:
 [[ 1.         -0.66666667  0.33333333]
 [ 0.          0.33333333 -0.16666667]
 [ 0.          0.          0.5       ]]

Matrix A raised to power 3:
 [[ 1 26 12]
 [ 0 27 19]
 [ 0  0  8]]


In [163]:
# Matrix and vector products
# example of two matrixes, please

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

print("A.dot(B) = \n",A.dot(B))

# Solving equations and inverting matrices

a = np.array([[1, 2], [3, 4]])
b = np.array([8, 18])

print(("Solution of linear equations:", np.linalg.solve(a, b)))

# Special Functions
"""
numpy.linalg.norm():	Matrix or vector norm.
numpy.linalg.cond():	Compute the condition number of a matrix.
numpy.linalg.matrix_rank():	Return matrix rank of array using SVD method
numpy.linalg.cholesky():	Cholesky decomposition.
numpy.linalg.qr():	Compute the qr factorization of a matrix.
numpy.linalg.svd(): Singular Value Decomposition.
"""

A.dot(B) = 
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
('Solution of linear equations:', array([2., 3.]))
